version: '3.9'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: php-8.1/app
        container_name: app
        volumes:
            - './:/var/www/html'
            - './devops/php.ini:/usr/local/etc/php/conf.d/local.ini'
        tty: true
        networks:
            - proxy
    nginx:
        image: nginx:alpine
        container_name: app-nginx
        tty: true
        volumes:
            - './:/var/www/html'
            - './devops/nginx.conf:/etc/nginx/conf.d/default.conf'
        labels:
            - "traefik.enable=true"        
            - "traefik.docker.network=proxy"            
            - "traefik.http.routers.app.rule=Host(`app.docker.localhost`)"            
            - "traefik.http.routers.app.tls=true"                        
        networks:
            - proxy
    jatos:
        image: jatos/jatos:3.7.4
        container_name: jatos           
        environment:
            JATOS_DB_URL: 'jdbc:mysql://${DB_HOST}/jatos?characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
            JATOS_DB_USERNAME: '${DB_USERNAME}'
            JATOS_DB_PASSWORD: '${DB_PASSWORD}'
            JATOS_DB_DRIVER: com.mysql.cj.jdbc.Driver
            JATOS_JPA: mysqlPersistenceUnit
        labels:
            - "traefik.enable=true"        
            - "traefik.docker.network=proxy"            
            - "traefik.http.routers.jatos.rule=Host(`jatos.docker.localhost`)"            
            - "traefik.http.routers.jatos.tls=true"            
            - "traefik.http.services.jatos.loadbalancer.server.port=9000"
        networks:
            - proxy
        volumes:
            - 'jatos-assets:/opt/docker/study_assets_root'
            - 'jatos-uploads:/opt/docker/result_uploads'
            # - 'jatos-db:/opt/docker/database'
    db:
        image: 'mariadb:10.8.2-rc'
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mariadb-db:/var/lib/mysql'
            - './devops/my.cnf:/etc/mysql/my.cnf'
            - './devops/init:/docker-entrypoint-initdb.d'
        networks:
            - proxy
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
        labels:
            - "traefik.enable=true"        
            - "traefik.docker.network=proxy"            
            - "traefik.http.routers.myadmin.rule=Host(`myadmin.docker.localhost`)"            
            - "traefik.http.routers.myadmin.tls=true"  
        networks:
            - proxy
    reverse-proxy:
        image: traefik:v2.5
        container_name: traefik        
        security_opt:
        - no-new-privileges:true
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./devops/traefik/static.yml:/etc/traefik/traefik.yml:ro
            - ./devops/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
            - ./devops/traefik/certs:/etc/certs:ro
        networks:
            - proxy
volumes:
    mariadb-db:
        driver: local
    jatos-assets:
        driver: local
    jatos-uploads:
        driver: local
networks:
    proxy:
        external: false